// 泰语辅音数据
const consonants = [
  { char: "ก", roman: "k", name: "ko kai", class: "低辅音", sound: "/k/" },
  { char: "ข", roman: "kh", name: "kho khai", class: "高辅音", sound: "/kʰ/" },
  { char: "ฃ", roman: "kh", name: "kho khuat", class: "高辅音", sound: "/kʰ/" },
  { char: "ค", roman: "kh", name: "kho khwai", class: "低辅音", sound: "/kʰ/" },
  { char: "ฅ", roman: "kh", name: "kho khon", class: "低辅音", sound: "/kʰ/" },
  { char: "ฆ", roman: "kh", name: "kho rakhang", class: "低辅音", sound: "/kʰ/" },
  { char: "ง", roman: "ng", name: "ngo ngu", class: "低辅音", sound: "/ŋ/" },
  { char: "จ", roman: "ch", name: "cho chan", class: "中辅音", sound: "/tɕ/" },
  { char: "ฉ", roman: "ch", name: "cho ching", class: "高辅音", sound: "/tɕʰ/" },
  { char: "ช", roman: "ch", name: "cho chang", class: "低辅音", sound: "/tɕʰ/" },
  { char: "ซ", roman: "s", name: "so so", class: "低辅音", sound: "/s/" },
  { char: "ฌ", roman: "ch", name: "cho choe", class: "低辅音", sound: "/tɕʰ/" },
  { char: "ญ", roman: "y", name: "yo ying", class: "低辅音", sound: "/j/" },
  { char: "ฎ", roman: "d", name: "do chada", class: "中辅音", sound: "/d/" },
  { char: "ฏ", roman: "t", name: "to patak", class: "中辅音", sound: "/t/" },
  { char: "ฐ", roman: "th", name: "tho than", class: "高辅音", sound: "/tʰ/" },
  { char: "ฑ", roman: "th", name: "tho montho", class: "低辅音", sound: "/tʰ/" },
  { char: "ฒ", roman: "th", name: "tho phu tho", class: "低辅音", sound: "/tʰ/" },
  { char: "ณ", roman: "n", name: "no nen", class: "低辅音", sound: "/n/" },
  { char: "ด", roman: "d", name: "do dek", class: "中辅音", sound: "/d/" },
  { char: "ต", roman: "t", name: "to tao", class: "中辅音", sound: "/t/" },
  { char: "ถ", roman: "th", name: "tho thung", class: "高辅音", sound: "/tʰ/" },
  { char: "ท", roman: "th", name: "tho thahan", class: "低辅音", sound: "/tʰ/" },
  { char: "ธ", roman: "th", name: "tho thong", class: "低辅音", sound: "/tʰ/" },
  { char: "น", roman: "n", name: "no nu", class: "低辅音", sound: "/n/" },
  { char: "บ", roman: "b", name: "bo baimai", class: "中辅音", sound: "/b/" },
  { char: "ป", roman: "p", name: "po pla", class: "中辅音", sound: "/p/" },
  { char: "ผ", roman: "ph", name: "pho phung", class: "高辅音", sound: "/pʰ/" },
  { char: "ฝ", roman: "f", name: "fo fa", class: "高辅音", sound: "/f/" },
  { char: "พ", roman: "ph", name: "pho phan", class: "低辅音", sound: "/pʰ/" },
  { char: "ฟ", roman: "f", name: "fo fan", class: "低辅音", sound: "/f/" },
  { char: "ภ", roman: "ph", name: "pho sam phao", class: "低辅音", sound: "/pʰ/" },
  { char: "ม", roman: "m", name: "mo ma", class: "低辅音", sound: "/m/" },
  { char: "ย", roman: "y", name: "yo yak", class: "低辅音", sound: "/j/" },
  { char: "ร", roman: "r", name: "ro rua", class: "低辅音", sound: "/r/" },
  { char: "ล", roman: "l", name: "lo ling", class: "低辅音", sound: "/l/" },
  { char: "ว", roman: "w", name: "wo waen", class: "低辅音", sound: "/w/" },
  { char: "ศ", roman: "s", name: "so sala", class: "高辅音", sound: "/s/" },
  { char: "ษ", roman: "s", name: "so rusi", class: "高辅音", sound: "/s/" },
  { char: "ส", roman: "s", name: "so suea", class: "高辅音", sound: "/s/" },
  { char: "ห", roman: "h", name: "ho hip", class: "高辅音", sound: "/h/" },
  { char: "ฬ", roman: "l", name: "lo chula", class: "低辅音", sound: "/l/" },
  { char: "อ", roman: "o", name: "o ang", class: "中辅音", sound: "/ʔ/" },
  { char: "ฮ", roman: "h", name: "ho nok huk", class: "低辅音", sound: "/h/" },
];

// 泰语元音数据（基础元音符号）
const vowels = [
  { char: "◌ะ", roman: "a", name: "sara a", sound: "/a/" },
  { char: "◌า", roman: "aa", name: "sara aa", sound: "/aː/" },
  { char: "◌ิ", roman: "i", name: "sara i", sound: "/i/" },
  { char: "◌ี", roman: "ii", name: "sara ii", sound: "/iː/" },
  { char: "◌ึ", roman: "ue", name: "sara ue", sound: "/ɯ/" },
  { char: "◌ื", roman: "uee", name: "sara uee", sound: "/ɯː/" },
  { char: "◌ุ", roman: "u", name: "sara u", sound: "/u/" },
  { char: "◌ู", roman: "uu", name: "sara uu", sound: "/uː/" },
  { char: "เ◌ะ", roman: "e", name: "sara e", sound: "/e/" },
  { char: "เ◌", roman: "ee", name: "sara ee", sound: "/eː/" },
  { char: "แ◌ะ", roman: "ae", name: "sara ae", sound: "/ɛ/" },
  { char: "แ◌", roman: "aee", name: "sara aee", sound: "/ɛː/" },
  { char: "โ◌ะ", roman: "o", name: "sara o", sound: "/o/" },
  { char: "โ◌", roman: "oo", name: "sara oo", sound: "/oː/" },
  { char: "เ◌าะ", roman: "o", name: "sara o", sound: "/ɔ/" },
  { char: "◌อ", roman: "or", name: "sara or", sound: "/ɔː/" },
  { char: "เ◌อะ", roman: "oe", name: "sara oe", sound: "/ɤ/" },
  { char: "เ◌ิ", roman: "oe", name: "sara oe", sound: "/ɤ/" },
  { char: "เ◌อ", roman: "oer", name: "sara oer", sound: "/ɤː/" },
  { char: "เ◌ียะ", roman: "ia", name: "sara ia", sound: "/ia/" },
  { char: "เ◌ียว", roman: "iao", name: "sara iao", sound: "/iaːw/" },
  { char: "เ◌ือะ", roman: "uea", name: "sara uea", sound: "/ɯa/" },
  { char: "เ◌ือ", roman: "uea", name: "sara uea", sound: "/ɯaː/" },
  { char: "◌ัวะ", roman: "ua", name: "sara ua", sound: "/ua/" },
  { char: "◌ัว", roman: "ua", name: "sara ua", sound: "/uaː/" },
  { char: "ไ◌", roman: "ai", name: "sara ai", sound: "/aj/" },
  { char: "ใ◌", roman: "ai", name: "sara ai", sound: "/aj/" },
  { char: "เ◌า", roman: "ao", name: "sara ao", sound: "/aw/" },
  { char: "◌ำ", roman: "am", name: "sara am", sound: "/am/" },
  { char: "เ◌ย", roman: "oei", name: "sara oei", sound: "/ɤj/" },
];

const appData = {
  consonants: consonants,
  vowels: vowels,
};
